/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// 0x40023800 rcc , enables peripherals
	// 0x40023830 address offset for gpio enable (0 bit is for gpioa)
	// 0x40020000 gpioa address
	*((volatile uint32_t*)0x40023830) |= (1<<0); //by this line we enable gpioa
	*((volatile uint32_t*)0x40020000) |= (1<<10); //by this line we set 10s bit to 1, because we need 01 to set pin for output
	*((volatile uint32_t*)0x40020000) &= ~(1<<11); // set 11 bit 0, now gpioa is an output pin
	while(1){
        *((volatile uint32_t*)0x40020014) ^= (1 << 5); // toggle 5th bit
        for(volatile int i = 0; i < 5000000; i++);	//delay
	}
}
